version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
      # image: fastapi-image:1.0.3
    container_name: fastapi_container
    ports:
      - 80:80
    volumes:
      - dataset:/src/app/data/
    command: uvicorn app.main:app --host 0.0.0.0 --port 80

volumes:
  dataset:
  
      

